### ISSUE TITLE
Issue with release 1.2.103 

### ISSUE THREAD

**Issue by woutdenolf** [oasys-kit/OASYS1#10]
```
pkg_resources.DistributionNotFound: The 'xoppylib' distribution was not found and is required by the application
/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py:777: DistributionNotFound
```

https://gitlab.esrf.fr/workflow/ewoks/ewoksorange/-/jobs/362758

**Comment by lucarebuffi** [comment]
for a rapid fix, install it manually: /usr/local/bin/python3.6 -m pip install xoppylib --upgrade

We will check and fix the issue soon.

**Comment by lucarebuffi** [comment]
I have it fixed in OASYS1-1.2.107, you should relaunch OASYS and do the update to the internal libraries.

**Comment by woutdenolf** [comment]
Thanks, CI runs again!

**Comment by lucarebuffi** [comment]
Great, sorry about the inconvenience.
