### ISSUE TITLE
pass canvas_window to all widgets

### ISSUE THREAD

**Issue by srio** [oasys-kit/OASYS1#12]
Thanks!

**Comment by lucarebuffi** [comment]
Done. Oasys1 1.2.118

Every widget has a new variable canvas_main_window, that is available after instancing it (i.e. not in the __init__())

**Comment by lucarebuffi** [comment]
As soon as you put the GitHub widget in OASYS tools, I will try to load the url directly

**Comment by lucarebuffi** [comment]
BTW, we should raise the version of the Oasys package to 1.3.0

**Comment by srio** [comment]
I have added the widget to github ( https://github.com/oasys-kit/OASYS1/ )
I have not released it (waiting for you to check it and add the load button)
