### ISSUE TITLE
oasys install addons with "pip install --user" in windows

### ISSUE THREAD

**Issue by srio** [oasys-kit/OASYS1#13]
It looks that Oasys installs the addons with admin=False:

![image](https://user-images.githubusercontent.com/502315/228809099-eccc2b1f-73ea-46d1-afe7-dedb365c432b.png)

This causes some trouble finding some packages.

Because the windows installation is by default in \users\<user>\miniconda3, we believe that the installation should be done using "admin=True" to send the code to the miniconda3 directory (owned by the user) and not to another user directory.  

Juan & Manolo

**Comment by lucarebuffi** [comment]
It was done on purpose to fix other serious issues, but I don't remember exactly, it was a long time ago. 
If you want you can try to fix it, but before uploading ANY modification, be sure of executing thorough testing, on ALL the operative system, by installing from scratch the application (or the app in case of MAC) and then try, multiple times, to install, update, delete, reinstall add-ons.
