### ISSUE TITLE
creation of undesired files upon closing OASYS

### ISSUE THREAD

**Issue by rafaelcelestre** [oasys-kit/OASYS1#16]
On a Windows machine (Windows 11) when using OASYS 1.3 (all my widgets are the latest version - to the day of this issue) the following issue occurs after closing it:

```bash
XXX\miniconda3\lib\site-packages\oasys\canvas\__main__.py:18: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
XXX\miniconda3\lib\site-packages\oasys\canvas\__main__.py:455: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead
  class SaveWorkspaceObj(QObject):
File written to disk: xcrystal.bra
```

I noticed that this creates the following files:

```bash
xcrystal.bra
xoppy.inp
```

I have not used xoppy nor calculated any reflectivity curve from crystals or whatsoever.

This is nothing serious, though.

Cheers,

**Comment by lucarebuffi** [comment]
this cannot be avoided. They are produced by compiled binary files.
