### ISSUE TITLE
PyQt version

### ISSUE THREAD

**Issue by srio** [oasys-kit/OASYS1#5]
Hello Luca, 

is there any particular reason to force PyQt>=5.12? (you changed it on June 6th: 
   from  'PyQt5>=5.11.3',
    to 'PyQt5>=5.12', )

This PyQt5=5.12 version does not work for windows and neither for our debian8 installation at ESRF. 

When we update SRW from the add-ons, we get errors and we have to go back manually to PyQt5.11.3. This PyQt5=5.11.3 is the one that works fine for me. 

Is possible to revert to PyQt5>=5.11.3

Thanks, M

**Comment by lucarebuffi** [comment]
Yes there was. Could you please send me the errors so I can try to fix them?

**Comment by srio** [comment]
In windows it works for 5.12 :)

In debian 8 it says (when starting python -m oasys.canvas):

python: relocation error: /mntdirect/_scisoft/XRayOptics/OASYS1.1e_RNICE8/miniconda3/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5DBus.so.5: symbol dbus_message_get_allow_interactive_authorization, version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time reference


if we downgrade: 
pip install pyqt5==5.11.3 --upgrade
pip install oasys1==1.2.3 --upgrade
it works. 

I know this debian8 is a very old version, but is the one that supports more users of Oasys.... We still use miniconda because the virtual environment does not work with the system python that is 3.4.2!!

**Comment by lucarebuffi** [comment]
Yes but it doesn't make sense to downgrade to a bugged version only for debian8. We can make a if-else statement for this specific version in the Oasys setup.py.

You can also try to upgrade libqt5dbus in your system.

**Comment by lucarebuffi** [comment]
You should play with os and platform libraries:

import platform,os
print(os.name+'\n'+platform.system()+'\n'+platform.release())

**Comment by srio** [comment]
OK, can I add this piece of code in setup.py (and raise oasys1 version) ? :

```
try:
    import platform
    os_info = platform.linux_distribution()
    if os_info[0] == "debian":
        if float(os_info[1]) < 9:
            l1 = list(INSTALL_REQUIRES)
            for i,element in enumerate(l1):
                if "PyQt5" in element:
                    l1[i] = "PyQt5==5.11.3"
            INSTALL_REQUIRES = tuple(l1)
except:
    pass
```

**Comment by lucarebuffi** [comment]
go on
