### ISSUE TITLE
Python input issue

### ISSUE THREAD

**Issue by maltissimo** [oasys-kit/OASYS1#6]
Hey Luca, 

I am  some code which requires the user to input  couple of values in the OASYS Python script environment. 

If I do something like: 

my_input=input("input anything: ")
print(my_input)

I get: 

>>> 
Running script:
input anything: --------------------------------------------------------------------------------
EOFError                                      Traceback (most recent call last):
  File "/Applications/Oasys1.2.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "<string>", line 1, in <module>
EOFError: EOF when reading a line
>>> 

I tried the same in my Idle3 and PyCharm, it works. 

Any clues? 

Ciao

Matteo

**Comment by lucarebuffi** [comment]
Input from command prompt is not supported, since it is not a command prompt.

Use QInputDialog

https://www.tutorialspoint.com/pyqt/pyqt_qinputdialog_widget.htm
