### ISSUE TITLE
"Render surface shape" instrument for SHADOW widgets

### ISSUE THREAD

**Issue by SergeyRa** [oasys-kit/OASYS1#7]
There are some issues regarding the "Render surface shape" instrument available in SHADOW widgets for curved elements:
1) The "Render surface shape" becomes inactive when "Surface shape parameter" setting switches from "calculated" to "user defined"
2) When surface shape is given by conic coefficients, launching of ray tracing resets some of the coefficients (see attached ZIP with .ows file)
3) In some cases (e.g. refractor interfaces in "lens_elliptical.ows" from "OTHER_EXAMPLES" folder in tutorials), the "Render surface shape" instrument plots just empty axes (probably a scaling issue)

[render_shape.zip](https://github.com/oasys-kit/OASYS1/files/4174012/render_shape.zip)

**Comment by lucarebuffi** [comment]
There is no issue. The code behave exactly how it has been coded: the rendering works only when conic coefficients are defined. 
Regarding case number 3,  sometimes the 3D graphic library fails and in that case no surface is shown.

**Comment by lucarebuffi** [comment]
I redirect the raytracing issue in the ShadowOui repository.

**Comment by lucarebuffi** [comment]
https://github.com/oasys-kit/ShadowOui/issues/204

**Comment by lucarebuffi** [comment]
ShadowOui bug has been fixed in 1.5.38
